name: 'Prepare CI'
description: 'Setup Dagger and CI requirements'
inputs:
  dagger-sdk:  # id of input
    description: 'Install Dagger SDK'
    default: 'false'

outputs:
  package-url:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v3
    if: ${{ inputs.dagger-sdk == 'false' }}
    with:
      node-version: 16

  - name: Get required python version
    if: ${{ inputs.dagger-sdk == 'true' }}
    run: |
      [[ ! -f ./.python-version ]]\
          && echo "You must pinned the python version in file[.python-version]."\
          && exit 1

      echo "REQUIRED_PYTHON_VERSION=$(cat ./.python-version)" >> $GITHUB_ENV

  - uses: actions/setup-python@v4
    if: ${{ inputs.dagger-sdk == 'true' }}
    with:
      python-version: '${{ env.REQUIRED_PYTHON_VERSION }}'
      cache: 'pip'

  - name: Install Dagger Python SDK and other PIP packages
    if: ${{ inputs.dagger-sdk == 'true' }}
    run: |
      pip install pip install -r requirements.txt