name: CI/CD Workflow w/ Dagger

on: 
  workflow_dispatch:

  push:
    branches:
    - dagger
    paths:
    - src
    - package.json

env:
  PACKAGE_NAME: '@lktslionel/conf42-demo'


jobs:
  pipeline:
    if: ${{ github.ref_name == 'dagger' }}
    name: CI CD Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - uses: ./.github/actions/prepare
      with:
        dagger-sdk: true

    - name: Login to GitHub Packages NPM Registry
      env:
        PACKAGE_REGISTRY_TOKEN: ${{ github.token }}
      run: |
        ./scripts/prepare.sh

    - name: Run pipeline
      env:
        GIT_TOKEN: ${{ github.token }}
        PACKAGE_REGISTRY_TOKEN: ${{ github.token }}
      run: python tasks/cicd.py
