name: CI/CD Workflow

on: 
  workflow_dispatch:
    
  push:
    branches:
    - main
    paths:
    - src
    - package.json

jobs:
  pipeline:
    name: CI CD Pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare CI env
      uses: ./.github/actions/prepare

    - name: Login to GitHub Packages NPM Registry
      env:
        PACKAGE_REGISTRY_TOKEN: ${{ github.token }}
      run: |
        ./scripts/prepare.sh

    - name: Install deps
      run: |
        npm ci

    - name: Bump version
      run: |
        npm version prerelease --preid=rc

    - name: Run build
      run: |
        npm run build

    - name: Run tests
      run: |
        npm run test

    - name: Publish package
      run: |
        npm publish

    - name: Export package version as env
      run: |
        pkg_name="$(jq -r '.name' package.json)"
        pkg_version="$(npm version --json | jq -r --arg pkg "${pkg_name}" '.[$pkg]')"

        echo "PKG_VERSION=${pkg_version}" >> $GITHUB_ENV

    - name: Commit changes
      run: |
        git push origin ${{ github.ref_name }}
        git push origin v${{ env.PKG_VERSION }}