name: CI/CD Workflow w/ Dagger

on: 
  workflow_dispatch:

env:
  PACKAGE_NAME: '@lktslionel/conf42-demo'

jobs:
  pipeline:
    name: CI CD Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - uses: ./.github/actions/prepare
      with:
        dagger-sdk: true

    - name: Run pipeline
      env:
        PACKAGE_REGISTRY_TOKEN: ${{ github.token }}
      run: python tasks/cicd.py
